"""add violation review fields

Revision ID: 245356b7598f
Revises: 934a649f4eb5
Create Date: 2026-06-18 18:16:20.815375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

review_status_enum = postgresql.ENUM(
    'pending', 'confirmed', 'dismissed', name='violation_review_status'
)


revision: str = '245356b7598f'
down_revision: Union[str, None] = '934a649f4eb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('human_reviews', sa.Column('violation_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_human_reviews_violation_id'), 'human_reviews', ['violation_id'], unique=False)
    op.create_foreign_key(None, 'human_reviews', 'violations', ['violation_id'], ['id'], ondelete='SET NULL')
    # Explicitly create the enum type (op.add_column won't auto-create it).
    review_status_enum.create(op.get_bind(), checkfirst=True)
    # server_default backfills existing rows to 'pending'; new rows use the model default.
    op.add_column('violations', sa.Column('review_status', review_status_enum, nullable=False, server_default='pending'))
    op.add_column('violations', sa.Column('review_note', sa.Text(), nullable=True))
    op.add_column('violations', sa.Column('reviewed_by', sa.String(), nullable=True))
    op.add_column('violations', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_violations_review_status'), 'violations', ['review_status'], unique=False)
    op.create_foreign_key(None, 'violations', 'users', ['reviewed_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'violations', type_='foreignkey')
    op.drop_index(op.f('ix_violations_review_status'), table_name='violations')
    op.drop_column('violations', 'reviewed_at')
    op.drop_column('violations', 'reviewed_by')
    op.drop_column('violations', 'review_note')
    op.drop_column('violations', 'review_status')
    review_status_enum.drop(op.get_bind(), checkfirst=True)
    op.drop_constraint(None, 'human_reviews', type_='foreignkey')
    op.drop_index(op.f('ix_human_reviews_violation_id'), table_name='human_reviews')
    op.drop_column('human_reviews', 'violation_id')
    # ### end Alembic commands ###
